# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bbfb41365dd6e513cad1c07b64bca4da49593011941c3cb8e953faa418abc9ba1d8dad375963489b79491599637b9cf281955742b3521b7296943c03b94e953

test:
  secret_key_base: 731fd201ac5f43c259e19918fe4b6afdb9e9665c5acd7b8adb3e963e9ba0122df89e00a12a40204040a84cbec97e848ef96359439e7ec6d886bc3a96be5f8eae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
